[versions]
anvil = "0.4.0-SNAPSHOT"
kotlin = "1.9.21"

[libraries]
adventure-bom = "net.kyori:adventure-bom:4.16.0"
anvil-core = { module = "org.anvilpowered:anvil-core", version.ref = "anvil" }
anvil-velocity = { module = "org.anvilpowered:anvil-velocity", version.ref = "anvil" }
brigadier = "com.mojang:brigadier:1.0.18"
discord-jda = "net.dv8tion:JDA:5.0.0-beta.20"
discord-webhooks = "club.minnced:discord-webhooks:0.8.4"
driver-mariadb = "org.mariadb.jdbc:mariadb-java-client:3.3.2"
driver-postgresql = "org.postgresql:postgresql:42.7.1"
kotest = "io.kotest:kotest-runner-junit5-jvm:5.5.4"
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.2"
luckperms = "net.luckperms:api:5.4"
velocity = "com.velocitypowered:velocity-api:3.1.1"

[plugins]
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = "org.jlleitschuh.gradle.ktlint:11.6.1"
shadow = "com.github.johnrengelman.shadow:8.1.1"
sponge = "org.spongepowered.gradle.plugin:2.1.1"
