[versions]
anvil = "0.4.0-SNAPSHOT"
kotlin = "2.0.0"
log4j = "2.23.1"

[libraries]
adventure-bom = "net.kyori:adventure-bom:4.16.0"
anvil-core = { module = "org.anvilpowered:anvil-core", version.ref = "anvil" }
anvil-velocity = { module = "org.anvilpowered:anvil-velocity", version.ref = "anvil" }
discord-jda = "net.dv8tion:JDA:5.0.0-beta.20"
discord-webhooks = "club.minnced:discord-webhooks:0.8.4"
driver-mariadb = "org.mariadb.jdbc:mariadb-java-client:3.3.2"
driver-postgresql = "org.postgresql:postgresql:42.7.2"
exposed-bom = "org.jetbrains.exposed:exposed-bom:0.50.1"
exposed-core = { module = "org.jetbrains.exposed:exposed-core" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time" }
kotest = "io.kotest:kotest-runner-junit5-jvm:5.9.1"
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3"
logging-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
logging-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
luckperms = "net.luckperms:api:5.4"
velocity = "com.velocitypowered:velocity-api:3.3.0-SNAPSHOT"

[bundles]
exposed = ["exposed-core", "exposed-dao", "exposed-jdbc", "exposed-java-time"]

[plugins]
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = "org.jlleitschuh.gradle.ktlint:11.6.1"
shadow = "io.github.goooler.shadow:8.1.7"
